### ISSUE TITLE
Email / password Delete Users

### ISSUE THREAD

**Issue by DannRomeR** [DannRomeR/Fireroom-v1.0.0#4]

**Comment by JesusRdr** [comment]
While testing the issue for deleting users with the Email - Password method, discovered the issue is in the Logout Button of the Navigation Activity.

**Comment by JesusRdr** [comment]
Issue is not allowing us to keep created users on the Firebase console. It's deleting even Google signed in users (this behavior was not happening when the Firestore branch was created).

**Comment by JesusRdr** [comment]
Issue remains at the following section at the NavigationActivity:  

            viewModel.signOut()

**Comment by JesusRdr** [comment]
corrected issue on the function signOut, at _AccountServiceImpl.kt_

override  fun signOut() {
        if (auth.currentUser == null) return
        **//  auth.currentUser!!.delete()**
        auth.signOut()
    }
